# Generated by Django 5.2.3 on 2025-06-11 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_name', models.CharField(max_length=300)),
                ('website_link_url', models.URLField()),
                ('certificate_logo', models.URLField()),
                ('cost_of_exam', models.FloatField()),
                ('difficulty_level', models.CharField(max_length=100)),
                ('salary_hike', models.FloatField()),
                ('pass_percent', models.FloatField()),
                ('description', models.TextField()),
                ('avg_prep_duration', models.FloatField()),
                ('student_rating', models.FloatField()),
                ('exam_duration', models.FloatField()),
                ('issued_by', models.CharField(max_length=200)),
                ('validity', models.IntegerField()),
                ('exam_format', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'certification',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('industry_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'industry',
            },
        ),
        migrations.CreateModel(
            name='CertificationCourses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=500)),
                ('course_link', models.URLField()),
                ('cost', models.FloatField()),
                ('certification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.certifications')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Niche',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('niche_name', models.CharField(max_length=100)),
                ('industry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.industry')),
            ],
            options={
                'db_table': 'niche',
            },
        ),
        migrations.AddField(
            model_name='certifications',
            name='niche_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.niche'),
        ),
    ]
