# Generated by Django 5.2.3 on 2025-06-11 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificationcourses',
            old_name='certification_id',
            new_name='certification',
        ),
        migrations.RenameField(
            model_name='certifications',
            old_name='niche_id',
            new_name='niche',
        ),
        migrations.RenameField(
            model_name='niche',
            old_name='industry_id',
            new_name='industry',
        ),
    ]
